
[[main]]
  name = "EDRLab Members website"
  identifier = "edrlabmember"
  weight = -108

[[main]]
  parent = "edrlabmember"
  name = "Browse Members"
  url = ""
  weight = -110

[[main]]
  parent = "edrlabmember"
  name = "About"
  url = "about/"
  weight = 50

[[main]]
  parent = "edrlabmember"
  name = "Becoming a Member"
  url = "https://www.edrlab.org/become-a-member/"
  weight = 10

[[main]]
  parent = "edrlabmember"
  name = "Collaborations"
  url = "/igs/"
  weight = 10

# [[main]]
# name = "Back to edrlab webpage"
# url = "https://www.edrlab.org"
# weight = 100

  [[social]]
  name = "rss"
  weight = 4
  url = "index.xml"


# Submenus are done this way: parent -> identifier
[[main]]
  name = "Main EDRLab website"
  identifier = "edrlaborg"
  weight = -108
[[main]]
  parent = "edrlaborg"
  name = "About"
  url = "https://www.edrlab.org/about/"
  weight = -90
[[main]]
  parent = "edrlaborg"
  name = "Summit"
  url = "https://www.edrlab.org/events/digital-publishing-summit-2023/"
  weight = -80
[[main]]
  parent = "edrlaborg"
  name = "LCP"
  url = "https://www.edrlab.org/readium-lcp/"
  weight = -70
[[main]]
  parent = "edrlaborg"
  name = "Standards"
  url = "https://www.edrlab.org/open-standards/"
  weight = -60
[[main]]
  parent = "edrlaborg"
  name = "Accessibility"
  url = "https://www.edrlab.org/accessibility/"
  weight = -40
[[main]]
  parent = "edrlaborg"
  name = "News"
  url = "https://www.edrlab.org/news/"
  weight = -30
[[main]]
  parent = "edrlaborg"
  name = "Contact"
  url = "https://www.edrlab.org/contact/"
  weight = -20

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/edrlab"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/edrlab_org"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/company/european-digital-reading-lab"



# [[main]]
#   name = "Archives"
#   url = "post/rich-content/"
#   weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"



# social menu links

# [[social]]
#   name = "github"
#   type = "social"
#   weight = 1
#   url = "https://github.com/#"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"


# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"