[[main]]
  name = "Members"
  url = ""
  weight = -110

# [[main]]
#   name = "Back to edrlab webpage"
#   url = "https://www.edrlab.org"
#   weight = -100

[[main]]
  name = "About"
  url = "https://www.edrlab.org/about/"
  weight = -90

[[main]]
  name = "Summit"
  url = "https://www.edrlab.org/events/digital-publishing-summit-2023/"
  weight = -80

[[main]]
  name = "LCP"
  url = "https://www.edrlab.org/readium-lcp/"
  weight = -70

[[main]]
  name = "Standards"
  url = "https://www.edrlab.org/open-standards/"
  weight = -60

[[main]]
  name = "Software"
  url = "https://www.edrlab.org"
  weight = -50

[[main]]
  name = "Accessibility"
  url = "https://www.edrlab.org/accessibility/"
  weight = -40

[[main]]
  name = "News"
  url = "https://www.edrlab.org/news/"
  weight = -30

[[main]]
  name = "Contact"
  url = "https://www.edrlab.org/contact/"
  weight = -20

[[main]]
  name = "Membership"
  url = "https://www.edrlab.org/become-a-member/"
  weight = -10

# [[main]]
#   name = "Archives"
#   url = "post/rich-content/"
#   weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

# [[social]]
#   name = "github"
#   type = "social"
#   weight = 1
#   url = "https://github.com/#"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"